/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageLoad: typeof import('./src/components/ImageLoad.vue')['default']
    LoadFonts: typeof import('./src/components/LoadFonts.vue')['default']
    PosterForm: typeof import('./src/components/PosterForm.vue')['default']
    PosterSearch: typeof import('./src/components/PosterSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TemplateOne: typeof import('./src/components/Template-One.vue')['default']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TOption: typeof import('tdesign-vue-next')['Option']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
